In [680]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

I=pd.read_csv(r"C:\Users\loveo\OneDrive\Desktop\Coursera\Machine Learning\Regression\insurance.csv")

X=I.iloc[:, :-1].values
y=I.iloc[:,-1].values

print(X)
y = y.reshape(len(y),1)
print(y)

[[19 'female' 27.9 0 'yes' 'southwest']
 [18 'male' 33.77 1 'no' 'southeast']
 [28 'male' 33.0 3 'no' 'southeast']
 ...
 [18 'female' 36.85 0 'no' 'southeast']
 [21 'female' 25.8 0 'no' 'southwest']
 [61 'female' 29.07 0 'yes' 'northwest']]
[[16884.92]
 [ 1725.55]
 [ 4449.46]
 ...
 [ 1629.83]
 [ 2007.94]
 [29141.36]]


Data preprocessing

Feature scaling

In [681]:
from sklearn.preprocessing import StandardScaler
sc_X= StandardScaler()
X[:,[0,2]] = sc_X.fit_transform(X[:,[0,2]] )

print(X)
print(y.shape)

[[-1.4387642602644821 'female' -0.45332000146019785 0 'yes' 'southwest']
 [-1.5099654504939408 'male' 0.5096210969173165 1 'no' 'southeast']
 [-0.7979535481993532 'male' 0.38330684721532526 3 'no' 'southeast']
 ...
 [-1.5099654504939408 'female' 1.014878095725279 0 'no' 'southeast']
 [-1.2963618798055645 'female' -0.797813409738354 0 'no' 'southwest']
 [1.5516857293727864 'female' -0.2613879597052247 0 'yes' 'northwest']]
(1338, 1)


In [682]:
#encoding
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Specify the columns to one-hot encode
columns = [1, 4, 5]  # Adjust these indices based on your dataset

# Create a ColumnTransformer with OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), columns)], remainder='passthrough')

# Apply the ColumnTransformer to the data
X = np.array(ct.fit_transform(X))

print(X)
print(X.shape)
print(y.shape)

[[1.0 0.0 0.0 ... -1.4387642602644821 -0.45332000146019785 0]
 [0.0 1.0 1.0 ... -1.5099654504939408 0.5096210969173165 1]
 [0.0 1.0 1.0 ... -0.7979535481993532 0.38330684721532526 3]
 ...
 [1.0 0.0 1.0 ... -1.5099654504939408 1.014878095725279 0]
 [1.0 0.0 1.0 ... -1.2963618798055645 -0.797813409738354 0]
 [1.0 0.0 0.0 ... 1.5516857293727864 -0.2613879597052247 0]]
(1338, 11)
(1338, 1)


Data split

In [683]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state =0)
print (X_train.shape)


(1070, 11)


In [684]:
#Training the multiple linear regression model
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

#predicting 
y_pred = (regressor.predict(X_test))


np.set_printoptions(precision=5)

print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

print(regressor.predict(([[0,1,1,0,0,0,1,0,-0.7979535482,0.3833068472,3]])))


[[11008.       9724.53   ]
 [ 9728.       8547.6913 ]
 [37632.      45702.02235]
 [16384.      12950.0712 ]
 [ 6912.       9644.2525 ]
 [ 3840.       4500.33925]
 [ 1920.       2198.18985]
 [14464.      11436.73815]
 [ 9088.       7537.1639 ]
 [ 7296.       5425.02335]
 [ 4352.       6753.038  ]
 [10240.      10493.9458 ]
 [ 9088.       7337.748  ]
 [ 4096.       4185.0979 ]
 [27392.      18310.742  ]
 [10752.      10702.6424 ]
 [11136.      12523.6048 ]
 [ 6144.       3490.5491 ]
 [ 8064.       6457.8434 ]
 [26752.      33475.81715]
 [32768.      23967.38305]
 [14464.      12643.3778 ]
 [11904.      23045.56616]
 [31872.      23065.4207 ]
 [ 4352.       1674.6323 ]
 [ 9344.       4667.60765]
 [ 1152.       3732.6251 ]
 [ 9984.       7682.67   ]
 [ 4096.       3756.6216 ]
 [10240.       8413.46305]
 [ 8960.       8059.6791 ]
 [39552.      48970.2476 ]
 [15744.      12979.358  ]
 [13952.      20630.28351]
 [24448.      14571.8908 ]
 [ 5504.       4137.5227 ]
 [12544.       8347.1643 ]
 

In [685]:

from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
print(r2)


0.7979523766348712


In [686]:
# Polynomial regression model
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg = PolynomialFeatures(degree = 2)
X_poly = poly_reg.fit_transform(X_train)
regressor = LinearRegression()
regressor.fit(X_poly, y_train)

y_pred = regressor.predict(poly_reg.transform(X_test))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
print(r2)
print(regressor.predict(poly_reg.transform([[0,1,1,0,0,0,1,0,-0.7979535482,0.3833068472,3]])))

[[11510.    9724.53]
 [10334.    8547.69]
 [50016.   45702.02]
 [15102.   12950.07]
 [ 7704.    9644.25]
 [ 4794.    4500.34]
 [ 4586.    2198.19]
 [14624.   11436.74]
 [10430.    7537.16]
 [ 8452.    5425.02]
 [ 8626.    6753.04]
 [11908.   10493.95]
 [ 8798.    7337.75]
 [ 5758.    4185.1 ]
 [25132.   18310.74]
 [12586.   10702.64]
 [13066.   12523.6 ]
 [ 5850.    3490.55]
 [ 9064.    6457.84]
 [27980.   33475.82]
 [26346.   23967.38]
 [14918.   12643.38]
 [11460.   23045.57]
 [29558.   23065.42]
 [ 3430.    1674.63]
 [ 7034.    4667.61]
 [ 4132.    3732.63]
 [ 9552.    7682.67]
 [ 5348.    3756.62]
 [11150.    8413.46]
 [10680.    8059.68]
 [52470.   48970.25]
 [14698.   12979.36]
 [11814.   20630.28]
 [14422.   14571.89]
 [ 6206.    4137.52]
 [10260.    8347.16]
 [37204.   51194.56]
 [36592.   40003.33]
 [ 2602.    1880.49]
 [ 6008.    5458.05]
 [ 5210.    2867.12]
 [24812.   20149.32]
 [48252.   47496.49]
 [35122.   36149.48]
 [ 6446.   26018.95]
 [12578.   19749.38]
 [ 8692.    6

In [687]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
print(r2)

print(regressor.predict(([[0,1,1,0,0,0,1,0,-0.7979535482,0.3833068472,3]])))


[[10797.34  9724.53]
 [ 8569.86  8547.69]
 [42983.46 45702.02]
 [13429.04 12950.07]
 [ 8688.86  9644.25]
 [21984.47  4500.34]
 [ 2196.47  2198.19]
 [10848.13 11436.74]
 [ 7209.49  7537.16]
 [ 4433.92  5425.02]
 [ 4766.02  6753.04]
 [ 8932.08 10493.95]
 [32108.66  7337.75]
 [ 4415.16  4185.1 ]
 [35147.53 18310.74]
 [10381.48 10702.64]
 [12323.94 12523.6 ]
 [24671.66  3490.55]
 [ 6455.86  6457.84]
 [33900.65 33475.82]
 [24869.84 23967.38]
 [12269.69 12643.38]
 [10197.77 23045.57]
 [24915.22 23065.42]
 [ 1391.53  1674.63]
 [20277.81  4667.61]
 [ 2680.95  3732.63]
 [ 7209.49  7682.67]
 [ 3736.46  3756.62]
 [ 8116.27  8413.46]
 [ 7201.7   8059.68]
 [47896.79 48970.25]
 [13462.52 12979.36]
 [10226.28 20630.28]
 [14283.46 14571.89]
 [ 3866.86  4137.52]
 [ 8978.19  8347.16]
 [38511.63 51194.56]
 [39983.43 40003.33]
 [ 2207.7   1880.49]
 [21984.47  5458.05]
 [ 3866.86  2867.12]
 [21659.93 20149.32]
 [49577.66 47496.49]
 [36307.8  36149.48]
 [ 3579.83 26018.95]
 [10381.48 19749.38]
 [ 6389.38  6

In [688]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(X_train,y_train)

y_pred = regressor.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
print(r2)

print(regressor.predict(([[0,1,1,0,0,0,1,0,-0.7979535482,0.3833068472,3]])))


[[ 9884.67  9724.53]
 [ 8617.73  8547.69]
 [44864.83 45702.02]
 [13259.2  12950.07]
 [11039.76  9644.25]
 [11594.86  4500.34]
 [ 2022.11  2198.19]
 [10304.93 11436.74]
 [ 7226.52  7537.16]
 [ 7959.49  5425.02]
 [ 8420.12  6753.04]
 [17452.43 10493.95]
 [ 9706.03  7337.75]
 [ 6932.86  4185.1 ]
 [23587.36 18310.74]
 [13635.41 10702.64]
 [13527.28 12523.6 ]
 [ 8727.22  3490.55]
 [ 6596.5   6457.84]
 [34022.75 33475.82]
 [23550.02 23967.38]
 [12607.06 12643.38]
 [13580.03 23045.57]
 [28164.81 23065.42]
 [ 1584.52  1674.63]
 [10464.39  4667.61]
 [13190.81  3732.63]
 [ 7184.23  7682.67]
 [ 3758.19  3756.62]
 [ 8693.96  8413.46]
 [ 7413.67  8059.68]
 [48838.78 48970.25]
 [14940.99 12979.36]
 [10391.48 20630.28]
 [15372.98 14571.89]
 [ 3879.61  4137.52]
 [ 8304.6   8347.16]
 [37592.5  51194.56]
 [40541.99 40003.33]
 [ 3988.63  1880.49]
 [11083.67  5458.05]
 [ 2925.14  2867.12]
 [20564.89 20149.32]
 [48190.46 47496.49]
 [37212.77 36149.48]
 [ 7664.52 26018.95]
 [13635.41 19749.38]
 [ 6738.33  6

C:\Users\loveo\AppData\Local\Temp\ipykernel_644\2867889076.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  regressor.fit(X_train,y_train)
