In [191]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

I=pd.read_csv(r"C:\Users\loveo\OneDrive\Desktop\Coursera\Machine Learning\Regression\insurance.csv")

X=I.iloc[:, :-1].values
y=I.iloc[:,-1].values

print(X)
y = y.reshape(len(y),1)
print(y)

[[19 'female' 27.9 0 'yes' 'southwest']
 [18 'male' 33.77 1 'no' 'southeast']
 [28 'male' 33.0 3 'no' 'southeast']
 ...
 [18 'female' 36.85 0 'no' 'southeast']
 [21 'female' 25.8 0 'no' 'southwest']
 [61 'female' 29.07 0 'yes' 'northwest']]
[[16884.924 ]
 [ 1725.5523]
 [ 4449.462 ]
 ...
 [ 1629.8335]
 [ 2007.945 ]
 [29141.3603]]


Data preprocessing

Feature scaling

In [192]:
from sklearn.preprocessing import StandardScaler
sc_X= StandardScaler()
X[:,[0,2]] = sc_X.fit_transform(X[:,[0,2]] )

print(X.shape)
print(y.shape)


(1338, 6)
(1338, 1)


In [193]:
from sklearn.preprocessing import LabelEncoder
columns = [1, 4, 5] 
l=LabelEncoder()
for i in columns:
    X[:,i]=l.fit_transform(X[:,i])
print(X)
print(X.shape)
print(y.shape)


[[-1.4387642602644821 0 -0.45332000146019785 0 1 3]
 [-1.5099654504939408 1 0.5096210969173165 1 0 2]
 [-0.7979535481993532 1 0.38330684721532526 3 0 2]
 ...
 [-1.5099654504939408 0 1.014878095725279 0 0 2]
 [-1.2963618798055645 0 -0.797813409738354 0 0 3]
 [1.5516857293727864 0 -0.2613879597052247 0 1 1]]
(1338, 6)
(1338, 1)


Data split

In [194]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state =0)
print (X_train.shape)


(1070, 6)


In [195]:
#Training the multiple linear regression model
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

#predicting 
y_pred = (regressor.predict(X_test))


np.set_printoptions(precision=5)

print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


print(regressor.predict(([[-1.4387642602644821, 0,-0.45332000146019785, 0, 1, 3 ]])))

from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
print(r2)

[[ 1.10172e+04  9.72453e+03]
 [ 9.78753e+03  8.54769e+03]
 [ 3.79948e+04  4.57020e+04]
 [ 1.61228e+04  1.29501e+04]
 [ 6.93076e+03  9.64425e+03]
 [ 3.96902e+03  4.50034e+03]
 [ 1.55178e+03  2.19819e+03]
 [ 1.42832e+04  1.14367e+04]
 [ 8.95343e+03  7.53716e+03]
 [ 7.43195e+03  5.42502e+03]
 [ 4.54458e+03  6.75304e+03]
 [ 1.02473e+04  1.04939e+04]
 [ 8.65711e+03  7.33775e+03]
 [ 4.12620e+03  4.18510e+03]
 [ 2.78113e+04  1.83107e+04]
 [ 1.10396e+04  1.07026e+04]
 [ 1.12514e+04  1.25236e+04]
 [ 6.03101e+03  3.49055e+03]
 [ 8.17339e+03  6.45784e+03]
 [ 2.70394e+04  3.34758e+04]
 [ 3.35778e+04  2.39674e+04]
 [ 1.42671e+04  1.26434e+04]
 [ 1.16850e+04  2.30456e+04]
 [ 3.24069e+04  2.30654e+04]
 [ 4.41465e+03  1.67463e+03]
 [ 9.14607e+03  4.66761e+03]
 [ 1.12787e+03  3.73263e+03]
 [ 1.00891e+04  7.68267e+03]
 [ 4.08783e+03  3.75662e+03]
 [ 1.03569e+04  8.41346e+03]
 [ 8.96224e+03  8.05968e+03]
 [ 4.02453e+04  4.89702e+04]
 [ 1.54779e+04  1.29794e+04]
 [ 1.36671e+04  2.06303e+04]
 [ 2.47415e+04

In [196]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
print(r2)

print(regressor.predict(([[-1.4387642602644821, 0,-0.45332000146019785, 0, 1, 3]])))


[[ 9487.6442   9724.53   ]
 [21232.18226  8547.6913 ]
 [44202.6536  45702.02235]
 [13143.86485 12950.0712 ]
 [ 9566.9909   9644.2525 ]
 [21984.47061  4500.33925]
 [ 2196.4732   2198.18985]
 [12797.20962 11436.73815]
 [ 7151.092    7537.1639 ]
 [ 4433.9159   5425.02335]
 [ 4766.022    6753.038  ]
 [30284.64294 10493.9458 ]
 [ 7345.7266   7337.748  ]
 [ 4571.41305  4185.0979 ]
 [35147.52848 18310.742  ]
 [ 8442.667   10702.6424 ]
 [12124.9924  12523.6048 ]
 [20277.80751  3490.5491 ]
 [ 6455.86265  6457.8434 ]
 [33907.548   33475.81715]
 [24869.8368  23967.38305]
 [12269.68865 12643.3778 ]
 [10355.641   23045.56616]
 [24915.22085 23065.4207 ]
 [ 1391.5287   1674.6323 ]
 [20277.80751  4667.60765]
 [ 2680.9493   3732.6251 ]
 [ 7151.092    7682.67   ]
 [ 3645.0894   3756.6216 ]
 [28340.18885  8413.46305]
 [ 7151.092    8059.6791 ]
 [47896.79135 48970.2476 ]
 [13462.52    12979.358  ]
 [10085.846   20630.28351]
 [14283.4594  14571.8908 ]
 [ 3757.8448   4137.5227 ]
 [ 8978.1851   8347.1643 ]
 

In [197]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(X_train,y_train)

y_pred = regressor.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
print(r2)

print(regressor.predict(([[-1.4387642602644821, 0,-0.45332000146019785, 0, 1, 3]])))


[[ 9533.5127   9724.53   ]
 [ 9888.68072  8547.6913 ]
 [44797.09166 45702.02235]
 [13246.51538 12950.0712 ]
 [ 9187.44924  9644.2525 ]
 [10793.99615  4500.33925]
 [ 2148.93331  2198.18985]
 [10684.36828 11436.73815]
 [ 8651.43041  7537.1639 ]
 [ 5484.16003  5425.02335]
 [ 6567.25965  6753.038  ]
 [18235.94801 10493.9458 ]
 [ 8356.75732  7337.748  ]
 [ 6186.11044  4185.0979 ]
 [25053.16566 18310.742  ]
 [13948.59484 10702.6424 ]
 [12588.7608  12523.6048 ]
 [ 7604.98124  3490.5491 ]
 [ 6459.97493  6457.8434 ]
 [33870.02168 33475.81715]
 [23676.94374 23967.38305]
 [12723.26468 12643.3778 ]
 [13785.50073 23045.56616]
 [27162.09145 23065.4207 ]
 [ 1652.84529  1674.6323 ]
 [ 9927.82804  4667.60765]
 [ 9548.67231  3732.6251 ]
 [ 7621.87054  7682.67   ]
 [ 3758.18952  3756.6216 ]
 [11003.77086  8413.46305]
 [ 7753.89509  8059.6791 ]
 [48779.05828 48970.2476 ]
 [14881.19776 12979.358  ]
 [12716.72844 20630.28351]
 [15824.31525 14571.8908 ]
 [ 4087.5232   4137.5227 ]
 [ 8361.29524  8347.1643 ]
 

C:\Users\loveo\AppData\Local\Temp\ipykernel_25148\104575146.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  regressor.fit(X_train,y_train)
